project_id = "xxfusqvbdgvaiopmdpbo"

[functions.analyze-game]
verify_jwt = false

[functions.fetch-steam-game]
verify_jwt = false

[functions.get-rankings]
verify_jwt = false

[functions.get-similar-gems]
verify_jwt = false

[functions.publish-steam-games]
verify_jwt = false

[functions.ingest-steam-game]
verify_jwt = false
